server:
  port: 8001
logging:
  config: classpath:log4j.xml
spring:
  datasource:
    db:
      jdbc-url: jdbc:mysql://localhost/fwkbd?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Madrid
      username: fwkuser
      password: CbCeUQdUO2khQti1pP25
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
